Repository eventoL/eventoL, pull requests merged in 2018-10, with the labels that each got.

#420 Feature/template custom para pycon 2018
  eventol/manager/static/manager/css/pyconar.css
  eventol/manager/templates/base-main-pycon.html
  eventol/manager/templates/base-pycon.html
  eventol/manager/templates/event/index-pycon.html
  eventol/manager/views.py
Labels: enhancement, future-release

#421 Custom template
  eventol/eventol/settings.py
  eventol/manager/migrations/0029_auto_20181005_0503.py
  eventol/manager/models.py
  eventol/manager/templates/event/index.html
  eventol/manager/views.py
Labels: enhancement, future-release

#423 update registration text. resolve #413
  eventol/conf/locale/es/LC_MESSAGES/django.po
  eventol/manager/templates/base-main.html
Labels: enhancement

#424 Custom form
  deploy/docker/README.md
  deploy/docker/docker-compose.yml
  eventol/eventol/settings.py
  eventol/eventol/urls.py
  eventol/manager/admin.py
  eventol/manager/migrations/0029_auto_20180929_1822.py
  eventol/manager/migrations/0030_attendee_customfields.py
  eventol/manager/migrations/0031_auto_20180930_1950.py
  eventol/manager/models.py
  eventol/manager/templates/forms/includes/built_form.html
  eventol/manager/templates/registration/attendee-registration.html
  eventol/manager/utils/forms.py
  eventol/manager/views.py
  requirements.txt
Labels: enhancement

#426 Fix #425 - Add postgres to testing environment (gitlabci and travis)
  .gitlab-ci.yml
  .travis.yml
Labels: bug

#428 When activities are private allow access to accepted ones
  eventol/manager/security.py
Labels: bug
