Repository eventoL/eventoL, pull requests merged in 2018-09, with the labels that each got.

#409 Update docker documentation
  deploy/docker/README.md
  docs/en/installation.md
  docs/es/installation.md
Labels: documentation-bug

#415 Reviewers
  .flake8
  eventol/manager/migrations/0028_reviewer.py
  eventol/manager/models.py
  eventol/manager/security.py
  eventol/manager/templates/activities/activities_home.html
  eventol/manager/templates/base-main.html
  eventol/manager/templates/event/review_people.html
  eventol/manager/templatetags/filters.py
  eventol/manager/urls/event.py
  eventol/manager/views.py
Labels: enhancement

#417 fix user comparision in is_activity_public()
  eventol/manager/security.py
Labels: bug
