Repository eventoL/eventoL, pull requests merged in 2019-06, with the labels that each got.

#546 Pytest
  .gitignore
  eventol/conf/locale/es/LC_MESSAGES/django.mo
  eventol/conf/locale/nb/LC_MESSAGES/django.mo
  eventol/conf/locale/nl/LC_MESSAGES/django.mo
  eventol/eventol/api.py
  eventol/eventol/urls.py
  eventol/front/package.json
  eventol/front/src/containers/Report/index.jsx
  eventol/front/src/utils/urls.js
  eventol/manager/tests/conftest.py
  eventol/manager/tests/constants.py
  eventol/manager/tests/test_api.py
  eventol/manager/tests/test_integration.py
  eventol/manager/tests/test_urls.py
  requirements-dev.txt
Labels: enhancement

#553 Update from Weblate
  eventol/conf/locale/es/LC_MESSAGES/django.mo
  eventol/conf/locale/es/LC_MESSAGES/django.po
  eventol/conf/locale/es/LC_MESSAGES/djangojs.po
  eventol/conf/locale/nl/LC_MESSAGES/django.mo
  eventol/conf/locale/nl/LC_MESSAGES/django.po
Labels: internationalization

#555 Update dependencies and update js environment
  .gitlab-ci.yml
  .hound.yml
  .travis.yml
  Dockerfile
  Makefile
  eventol/front/.babelrc
  eventol/front/.eslintrc.json
  eventol/front/.eslintrc.yaml
  eventol/front/.prettierrc
  eventol/front/.sass-lint-auto-fix.yml
  eventol/front/.sass-lint.yml
  eventol/front/babel.config.js
  eventol/front/package.json
  eventol/front/server.js
  eventol/front/webpack.base.config.js
  eventol/front/webpack.local-settings.js
  eventol/front/webpack.local.config.js
  eventol/front/webpack.prod.config.js
  eventol/front/yarn.lock
  requirements-dev.txt
Labels: UX/UI, enhancement, internal
