Repository eventoL/eventoL, pull requests merged in 2019-03, with the labels that each got.

#518 Develop
  docs/en/installation.md
  docs/es/installation.md
Labels: documentation-bug

#519 Actualizacion de traduccion de tag
  eventol/conf/locale/es/LC_MESSAGES/django.mo
  eventol/conf/locale/es/LC_MESSAGES/django.po
Labels: internationalization

#520 Remove collaboration tab in events without collaborators
  eventol/manager/templates/base-main.html
Labels: bug

#522 Autodeploy
  .gitlab-ci.yml
Labels: IT, docker, internal

#527 Replace Landscape with Codeclimate
  .codeclimate.yml
  .landscape.yaml
  .travis.yml
  README-es.md
  README.md
  docs/README-es.md
  docs/README.md
  docs/en/README.md
  docs/es/README.md
Labels: enhancement, internal
